{
  "success": false,
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/mythril/interfaces/cli.py\", line 967, in parse_args_and_execute\n    execute_command(\n  File \"/usr/local/lib/python3.10/dist-packages/mythril/interfaces/cli.py\", line 868, in execute_command\n    \"json\": report.as_json(),\n  File \"/usr/local/lib/python3.10/dist-packages/mythril/analysis/report.py\", line 304, in as_json\n    return json.dumps(result, sort_keys=True)\n  File \"/usr/lib/python3.10/json/__init__.py\", line 238, in dumps\n    **kw).encode(obj)\n  File \"/usr/lib/python3.10/json/encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib/python3.10/json/encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib/python3.10/json/encoder.py\", line 179, in default\n    raise TypeError(f'Object of type {o.__class__.__name__} '\nTypeError: Object of type bytes is not JSON serializable\n",
  "issues": []
}